import Header from "@/components/layouts/Header";
import "./globals.css";
import Footer from "@/components/layouts/Footer";
import {yekanBakh} from "@/utils/fonts";
export const metadata = {
  title: "Amlakito",
  description: "Generated by Amlakito",
};

export default function RootLayout({children}) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${yekanBakh.className} bg-background container mx-auto`}>
        <Header />
        <section className="min-h-screen">{children}</section>
        <Footer />
      </body>
    </html>
  );
}
