import "./globals.css";
import {yekanBakh} from "@/utils/fonts";
import Layout from "@/components/layouts/Layout";
export const metadata = {
  title: "Amlakito",
  description: "Generated by Amlakito",
};

export default function RootLayout({children}) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${yekanBakh.className} bg-background container mx-auto`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
